### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by SliceOfArdath** [nicoth-in/Dark-Space-Theme#11]
How to reproduce: open at least two tabs (of whatever you want). Move one of them in a second window, minimize the window.
The memory usage climbs at a rate of ~50Mb/s, and will not stop (i have reached 80go of usage twice now)
If you bring back said window, the memory is freed.

This bug was found on MacOS, firefox 111.0, aarch64. I have tried to reproduce it both with and without the theme, and found a leak only with the theme. During testing, I only had this theme (no extensions). 
This bug can be reproduced in nightly.
It seems also unique to this theme, I have tried other animated themes, both with and without nightly, without such issues.

**Comment by SliceOfArdath** [comment]
After a bit of search: it seems the issue may be related to using Gifs for animation? I will look further into it, and may take this to bugzilla. In the meantime, turning the asset into an animated PNG should fix it.

**Comment by SliceOfArdath** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1786247

**Comment by das-nagnag** [comment]
It took me days to figure out the root cause for my consistent memory leaking, until I found your issue so thanks for that. Following up on the bugzilla link you posted, something of note:
> Total system memory usage climbs steadily ***when window is completely covered*** and ***only released when it becomes visible***.

i.e.: this only happens when you have windows on your main or secondary monitor(s) that become obstructed/covered or inactive and the memory will be released when the window is brought to the front again. So alt/cmd-tabbing through all windows would be an easy way to free the memory.

I followed down that rabbit hole of the bug ticket and as it turns out, that appears to actually be an issue in Firefox, not necessarily in the theme. However, according to https://bugzilla.mozilla.org/show_bug.cgi?id=1828587 this appears to have been fixed. The fix will be rolled out with Firefox 112.0.2 which, according to https://whattrainisitnow.com/release/?version=112, is planned to be released in two days; though I have no idea whether it's actually going to happen on that date or not.

Either way, it doesn't seem to actually be an issue with the theme, strictly speaking (which also would be weird since it hasn't been updated since last year afaik and I only started to notice the memory leak a couple of days ago). Until the release of the patch version the recommended workaround would be to disable the theme.

**Comment by AvinashK13** [comment]
This issue still exists in firefox stable 114.0 on MacOS Ventura M1.
The memory usage is as high as 85GB for me now.

**Comment by das-nagnag** [comment]
> This issue still exists in firefox stable 114.0 on MacOS Ventura M1. The memory usage is as high as 85GB for me now.

@AvinashK13 according to the Mozilla Bugtracker that appears to be a regression of the previously fixed bug – see https://bugzilla.mozilla.org/show_bug.cgi?id=1830753
I reckon this will be fixed in the next minor or major version. Until then you might have to disable the theme or roll back to a previous version of Firefox that has worked. But again, realistically this is a bug in firefox and not *caused* by the theme.

**Comment by AvinashK13** [comment]
@das-nagnag thanks for the reply, yes I've disabled the theme as of now

**Comment by hvitoi** [comment]
I can reproduce it on Arch Linux on Wayland with firefox `115.0.3-1`.
Simply having a tab opened in a workspace other than the currently active one is enough to start the memory leak.

It took me weeks to discover. Depending on the kernel and mesa versions it eventually causes the whole system to freeze (my case).
